# Generated by Django 4.1.5 on 2023-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('urok1', models.CharField(max_length=30)),
                ('urok2', models.CharField(max_length=30)),
                ('urok3', models.CharField(max_length=30)),
                ('urok4', models.CharField(max_length=30)),
                ('urok5', models.CharField(max_length=30)),
                ('urok6', models.CharField(max_length=30)),
            ],
        ),
    ]
