# Generated by Django 4.1.5 on 2023-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasp',
            name='data',
            field=models.DateField(),
        ),
    ]
