# Generated by Django 4.1.5 on 2023-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(max_length=1)),
                ('homework', models.TextField()),
                ('url_task', models.CharField(max_length=250)),
                ('data_task', models.DateField()),
                ('predmet', models.CharField(max_length=20)),
            ],
        ),
    ]
