# Generated by Django 4.1.5 on 2023-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diareya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary_rasp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diary_rasp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diary_rasp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diary_rasp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diary_rasp5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diary_rasp6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_urok1', models.CharField(max_length=20)),
                ('diary_urok2', models.CharField(max_length=20)),
                ('diary_urok3', models.CharField(max_length=20)),
                ('diary_urok4', models.CharField(max_length=20)),
                ('diary_urok5', models.CharField(max_length=20)),
                ('diary_urok6', models.CharField(max_length=20)),
            ],
        ),
    ]
